# For all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: docker
    directories:
      - fpm
      - apache
    schedule:
      interval: "daily"
    labels:
      - "docker"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "php"
        update-types: ["version-update:semver-minor"]
    groups:
      php:
        patterns:
          - "php"
      php-extension-installer:
        patterns:
          - "mlocati/php-extension-installer"
      composer:
        patterns:
          - "composer/composer"
      node:
        patterns:
          - "node"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "github-actions"
    groups:
      specsnl-github-actions:
        patterns:
          - "specsnl/github-actions*"
